export const portfolioData = [
  {
    title: "Kolem krku",
    link: "https://kolem-krku.cz/",
    linkViewMore: "kolem-krku.cz",
    hasCaseStudy: true,
    slug: "kolemkrku",
    caseStudy: {
      subTitle: "Originální ručně šité kravaty, Kolem-krku.cz",
      year: 2022,
      technologies: ["Shoptet", "HTML", "CSS", "JavaScript", "jQuery"],
      images: [
        { img: "/moje_prace/kolemkrku.png", alt: "kolemkrku" },
        { img: "/moje_prace/kolemkrku1.png", alt: "kolemkrkunaled" },
        { img: "/public/moje_prace/kolemkrku2.png", alt: "alt" },
        { img: "/public/moje_prace/kolemkrku3.png", alt: "alt" },
      ],
      bgFromColor: "from-sky-600",
    },
    shortDecs: "shortDecs",
    images: [{ img: "/moje_prace/kolemkrku.png", alt: "kolemkrku" }],
  },
  {
    title: "Zodpovědná vyúka",
    link: "https://zodpovednavyuka.cz/",
    linkViewMore: "zodpovednavyuka.cz",
    hasCaseStudy: true,
    shortDecs: "shortDecs",
    slug: "zodpovednavyuka",
    images: [{ img: "/moje_prace/zv.png", alt: "alt" }],
    caseStudy: {
      bgFromColor: "from-amber-200",
      subTitle: "Originální ručně šité kravaty, Kolem-krku.cz",
      year: 2022,
      technologies: ["Shoptet", "HTML", "CSS", "JavaScript", "jQuery"],
      images: [
        { img: "/moje_prace/zv.png", alt: "kolemkrku" },
        { img: "/moje_prace/zv1.png", alt: "kolemkrkunaled" },
        { img: "/moje_prace/zv2.png", alt: "alt" },
        { img: "/moje_prace/zv3.png", alt: "alt" },
      ],
    },
  },
  {
    title: "Svou Cestou",
    link: "https://svoucestou.info/",
    linkViewMore: "svoucestou.info",
    hasCaseStudy: true,
    slug: "svoucestou",
    caseStudy: {
      subTitle: "Originální ručně šité kravaty, Kolem-krku.cz",
      year: 2022,
      technologies: ["Shoptet", "HTML", "CSS", "JavaScript", "jQuery"],
      images: [
        { img: "/moje_prace/zv.png", alt: "kolemkrku" },
        { img: "/moje_prace/zv1.png", alt: "kolemkrku" },
        { img: "/moje_prace/zv.png", alt: "kolemkrku" },
      ],
      bgFromColor: "from-green-500",
    },

    shortDecs: "shortDecsSvoucestou",
    images: [
      { img: "/moje_prace/zv.png", alt: "kolemkrku" },
      { img: "/moje_prace/zv.png", alt: "kolemkrku" },
    ],
  },
  {
    title: "Kolem krku",
    link: "https://kolem-krku.cz/",
    linkViewMore: "kolem-krku.cz",
    hasCaseStudy: false,
    shortDecs: "shortDecs",
    images: [{ img: "/moje_prace/zv.png", alt: "kolemkrku" }],
  },
];
